### ISSUE TITLE
HW connection details

### ISSUE THREAD

**Issue by kubeqz** [lhartmann/c2_prog_wifi#4]
Can you please describe what is your HW connection ? Are there any pull-ups required on C2D or C2CK ?
I'm trying to read data from FLASH and after few kBytes read it stops, with error 'broken link', at random address. I suspect there is something in HW I'm missing.

**Comment by lhartmann** [comment]
To be honest I never tried reading back from the IC, all I needed was to write to it.

Perhaps try changing pinMode(PIN_C2D, INPUT) to INPUT_PULLUP on c2d.h:38?

I don't have any PCBs accessible right now, so please let me know if it works for you so I can fix it.

**Comment by lhartmann** [comment]
Closing on inactivity.
